[build]
  command = "yarn workspace site build"
  functions = "functions"
  publish = "public"

[dev] 
  command = "yarn develop" # Command to start your dev server
  targetPort = 8000 # port the app runs on
  port = 5000 # port Netlify Dev runs on
  functionsPort = 34567
  publish = "public" # Folder with the static content for _redirect file

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  type = "netlify-plugin-gatsby-cache"
